//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        UI.WcfService.CompositeType GetDataUsingDataContract(UI.WcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<UI.WcfService.CompositeType> GetDataUsingDataContractAsync(UI.WcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipoCliente", ReplyAction="http://tempuri.org/IService1/GetTipoClienteResponse")]
        DTO.Entities.TipoCliente[] GetTipoCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipoCliente", ReplyAction="http://tempuri.org/IService1/GetTipoClienteResponse")]
        System.Threading.Tasks.Task<DTO.Entities.TipoCliente[]> GetTipoClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSituacaoCliente", ReplyAction="http://tempuri.org/IService1/GetSituacaoClienteResponse")]
        DTO.Entities.SituacaoCliente[] GetSituacaoCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSituacaoCliente", ReplyAction="http://tempuri.org/IService1/GetSituacaoClienteResponse")]
        System.Threading.Tasks.Task<DTO.Entities.SituacaoCliente[]> GetSituacaoClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientes", ReplyAction="http://tempuri.org/IService1/GetClientesResponse")]
        DTO.Entities.Cliente[] GetClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientes", ReplyAction="http://tempuri.org/IService1/GetClientesResponse")]
        System.Threading.Tasks.Task<DTO.Entities.Cliente[]> GetClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCliente", ReplyAction="http://tempuri.org/IService1/SaveClienteResponse")]
        string SaveCliente(DTO.Entities.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCliente", ReplyAction="http://tempuri.org/IService1/SaveClienteResponse")]
        System.Threading.Tasks.Task<string> SaveClienteAsync(DTO.Entities.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCliente", ReplyAction="http://tempuri.org/IService1/DeleteClienteResponse")]
        string DeleteCliente(int clienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCliente", ReplyAction="http://tempuri.org/IService1/DeleteClienteResponse")]
        System.Threading.Tasks.Task<string> DeleteClienteAsync(int clienteId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UI.WcfService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UI.WcfService.IService1>, UI.WcfService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public UI.WcfService.CompositeType GetDataUsingDataContract(UI.WcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<UI.WcfService.CompositeType> GetDataUsingDataContractAsync(UI.WcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public DTO.Entities.TipoCliente[] GetTipoCliente() {
            return base.Channel.GetTipoCliente();
        }
        
        public System.Threading.Tasks.Task<DTO.Entities.TipoCliente[]> GetTipoClienteAsync() {
            return base.Channel.GetTipoClienteAsync();
        }
        
        public DTO.Entities.SituacaoCliente[] GetSituacaoCliente() {
            return base.Channel.GetSituacaoCliente();
        }
        
        public System.Threading.Tasks.Task<DTO.Entities.SituacaoCliente[]> GetSituacaoClienteAsync() {
            return base.Channel.GetSituacaoClienteAsync();
        }
        
        public DTO.Entities.Cliente[] GetClientes() {
            return base.Channel.GetClientes();
        }
        
        public System.Threading.Tasks.Task<DTO.Entities.Cliente[]> GetClientesAsync() {
            return base.Channel.GetClientesAsync();
        }
        
        public string SaveCliente(DTO.Entities.Cliente cliente) {
            return base.Channel.SaveCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<string> SaveClienteAsync(DTO.Entities.Cliente cliente) {
            return base.Channel.SaveClienteAsync(cliente);
        }
        
        public string DeleteCliente(int clienteId) {
            return base.Channel.DeleteCliente(clienteId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteClienteAsync(int clienteId) {
            return base.Channel.DeleteClienteAsync(clienteId);
        }
    }
}
